title: Carolin Reichherzer
logo: /assets/img/Vive.jpeg
description: Hi, I'm Carolin! I'm a AR/VR researcher who loves exploring new ways people can interact with 3D spaces in ways that inspire and delight. 
show_downloads: false
google_analytics: UA-59119528-1
theme: jekyll-theme-minimal
