title: Carolin Reichherzer, PhD
logo: /assets/img/ProfileHead.jpg
description: Hi, I'm Carolin! I'm a Research Scientist in all things AR/VR. I am passionate about delivering novel AR/VR experiences for everyone that delight and connect people in new ways.
show_downloads: false
google_analytics: G-HEG2VRSWMF
theme: jekyll-theme-minimal
