title: Carolin Reichherzer
logo: /assets/img/reconstruction.png
description: PhD Candidate at the Australian Research Centre for Interactive Virtual Environments (ARCIVE)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
