title: Carolin Reichherzer, PhD
logo: /assets/img/ProfileHead.jpg
description: Hi, I'm Carolin! I'm a Senior Research Associate in all things AR/VR. I love exploring novel interactive experiences for immersive technologies in ways that inspire and delight.
show_downloads: false
google_analytics: G-HEG2VRSWMF
theme: jekyll-theme-minimal
