title: Carolin Reichherzer
logo: /assets/img/Vive.jpeg
description: Hi, I'm Carolin! I'm a PhD Candidate at the Australian Research Centre for Interactive and Virtual Environments (IVE) at the University of South Australia
show_downloads: false
google_analytics: UA-59119528-1
theme: jekyll-theme-minimal
