title: Carolin Reichherzer, PhD
logo: /assets/img/ProfileHead.jpg
description: Hi, I'm Carolin! I'm a Research Scientist and UX Researcher. I am passionate about delivering novel and meaningful user experiences for everyone. 
show_downloads: false
google_analytics: G-HEG2VRSWMF
theme: jekyll-theme-minimal
